---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  with_items:
    - firewalld

- name: Add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository exists
  stat:
    path: '/etc/yum.repos.d/docker-ce.repo'
    register: docker_ce_repo_exists
- name: Add Docker repository
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644
  when: docker_ce_repo_exists.stat.exists == False

- name: Configure Docker Edge repo
  ini_file:
    dest: '/etc/yum.repos.d/docker-ce.repo'
    section: 'docker-ce-stable'
    option: enabled
    value: '1'

