---
- name: Install Kubernetes basics
  package: 
    name: "{{item}}"
    state: installed
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
    - ebtables
    - ethtool
    - python-pip
    - docker-ce
    - etcd

- name: Pip Install Docker Py
  pip:
    name: docker-py

- name: Pull K8s Docker images
  docker_image:
    name: "{{item}}"
  with_items:
    - "gcr.io/google_containers/kube-apiserver-amd64:v1.8.2"
    - "gcr.io/google_containers/kube-controller-manager-amd64:v1.8.2"
    - "gcr.io/google_containers/kube-scheduler-amd64:v1.8.2"

- name: Enable systemd components
  systemd: 
    name: "{{item}}"
    enabled: yes
    state: started
  with_items:
    - etcd
    - docker
    - kubelet

